version: "3.9"

services:

  zookeeper:
    #image: bitnami/zookeeper:latest
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 2181:2181
    #volumes:
    #  - '/Users/phmacos/bancodedados/zookeper/data:/bitnami/zookeeper/data'
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_CLIENT_PORT: 2181
      TZ: 'America/Sao_Paulo'

  broker:
    #image: bitnami/kafka:latest
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    restart: on-failure
    ports:
      - 9092:9092
    #volumes:
    #  - '/Users/phmacos/bancodedados/kafka/data:/bitnami/kafka/data'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: 'PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ENABLE_KRAFT: no
      TZ: 'America/Sao_Paulo'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    depends_on:
      - zookeeper

#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    container_name: kafka-ui
#    depends_on:
#      - broker
#      - zookeeper
#    ports:
#      - "8086:8080"
#    restart: always
#    environment:
#      - KAFKA_CLUSTERS_0_NAME=kafka-test
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker:29092
#      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181